from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='cat'),
    path('recipes', views.recipes, name='recipes'),
    path('logout', views.recipes, name='logout'),
    path('plov', views.plov, name='plov'),
    path('chickencurry', views.chcr, name='chickcurr'),
    path('cesar', views.cesar, name='cesar'),
    path('shrimppasta', views.shrimppasta, name='shrimppasta'),
    path('shrimprice', views.shrimprice, name='shrimprice'),
    path('kartofragu', views.kartofragu, name='kartofragu'),
    path('draniki', views.draniki, name='draniki'),
    path('dereven', views.dereven, name='dereven'),
    path('pastapesto', views.pastapesto, name='pastapesto'),
    path('bolognese', views.bolognese, name='bolognese'),
    path('olivier', views.olivier, name='olivier'),
    path('mimosa', views.mimosa, name='mimosa'),
    path('chikenpineapple', views.chikenpineapple, name='chikenpineapple'),
    path('chinese', views.chinese, name='chinese'),
    path('goulash', views.goulash, name='goulash'),
    path('rukkbeef', views.rukkbeef, name='rukkbeef'),
    path('chakhokhbili', views.chakhokhbili, name='chakhokhbili'),
    path('risotto', views.risotto, name='risotto'),
    path('shawarma', views.shawarma, name='shawarma'),
    path('zapekanka', views.zapekanka, name='zapekanka'),
    path('lasagna', views.lasagna, name='lasagna'),
    path('wok', views.wok, name='wok'),
    path('greek', views.greek, name='greek'),
    path('mozzarukk', views.mozzarukk, name='mozzarukk'),
    path('stuffedpep', views.stuffedpep, name='stuffedpep'),
    path('chicksoup', views.chicksoup, name='chicksoup'),
    path('pizzamar', views.pizzamar, name='pizzamar'),
    path('shrimproll', views.shrimproll, name='shrimproll'),
    path('frenchsoup', views.frenchsoup, name='frenchsoup'),
    path('beefstroganoff', views.beefstroganoff, name='beefstroganoff'),


]
